### PR TITLE
Feat/ci compilation check

### PR DESCRIPTION
**Pull request by ttm02**
- adds CI that tests if all microbench testcases compile
- CI also check if all files are formated according to the .clang-format in the repo
- re-formated code to comply with new CI

### CODE REVIEW

**Comment by jplehr** [comment]
I didn't check all the code files, but the workflow definition seems fine.

**Comment by ahueck** [comment]
Is the workflow job for formatting exiting after the first defect? If yes, you should consider showing all defects first, before failing.

Nitpicky:
- Is it possible to ident the bash code for the checks, simply to improve readbility, e.g.,
```sh
for ...
  work...
  work...
done
```
- `Check code Formatting` -> formatting

**Comment by ttm02** [comment]
Why do you want to see all code formatting defects?
If I encounter a defect, I would just run clang-format on all new/changed files anyway.
by aborting at the first defect, we get slightly faster feedback form the CI

**Comment by ahueck** [comment]
> Why do you want to see all code formatting defects?

No technical reason, just a preference.

**Comment by jplehr** [comment]
Then we leave it with bailing out after the first violation is detected.

**Pull request merged**
